# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Numerical-Api CI/CD

on:
<<<<<<< HEAD
    push:
        branches: [main]
jobs:
    push_to_registry:
        name: Push Numerical-Api to Github
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Login Docker
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - name: Build Docker
              run: |
                  docker build . -t theboss38/numerical-api:latest
            - name: Push Docker
              run: |
                  docker push theboss38/numerical-api:latest
=======
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
>>>>>>> 0e19046701461f888614899a25b380ae4efbe10e
